export { default as Page } from './Page'
export { default as PageApp } from './PageApp'
export { default as PageBlog } from './PageBlog'
export { default as PageBlogs } from './PageBlogs'
export { default as PageCV } from './PageCV'
export { default as PageInfo } from './PageInfo'
export { default as PageSkills } from './PageSkills'
