name: "Deploy Development"

on:
  push:
    branches:
      - "main"

jobs:
  deploy:
    runs-on: ubuntu-latest
    name: Deploy Development
    steps:
      - uses: actions/checkout@v6
      - name: Setup Node.js
        uses: actions/setup-node@v6
        with:
          node-version: "24"
      - name: "Installare Vercel CLI"
        run: npm install -g vercel
      - name: "Deploy su Vercel"
        run: vercel --token=${{ secrets.VERCEL_TOKEN }} --yes


