name: "Deploy Production"

on:
  push:
    tags:
      - "*" # Attiva il workflow su tutti i tag

jobs:
  eslint:
    runs-on: ubuntu-latest
    name: Deploy
    steps:
      - uses: actions/checkout@v4
      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version: "22"
      - name: "Installare Vercel CLI"
        run: npm install -g vercel
      - name: "Deploy"
        run: vercel --prod --token=${{ secrets.VERCEL_TOKEN }} --yes