name: ChatGPT Code Review

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  review_code:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js 20
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install --legacy-peer-deps

      - name: Analyze code with ChatGPT
        id: chatgpt-review
        run: |
          # Send the changed code files to ChatGPT API and capture the response
          MODIFIED_FILES=$(git diff --name-only ${{ github.event.pull_request.base.sha }} ${{ github.sha }})
          for file in $MODIFIED_FILES; do
            if [[ $file == *.js || $file == *.ts || $file == *.jsx || $file == *.tsx ]]; then
              echo "Reviewing $file"
              FILE_CONTENT=$(cat $file)
              REVIEW=$(curl -X POST "https://api.openai.com/v1/chat/completions" \
              -H "Authorization: Bearer ${{ secrets.OPENAI_API_KEY }}" \
              -H "Content-Type: application/json" \
              -d '{
                    "model": "gpt-4",
                    "messages": [
                      {"role": "system", "content": "You are a helpful assistant reviewing code."},
                      {"role": "user", "content": "Analyze this code for logic and syntax errors: '"$FILE_CONTENT"'"}
                    ]
                  }')
              echo "ChatGPT Review: $REVIEW"
            fi
          done

      - name: Create PR comment with ChatGPT review
        uses: peter-evans/create-or-update-comment@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          issue-number: ${{ github.event.pull_request.number }}
          body: |
            ## ChatGPT Review

            Here are the insights for your code:
            - **Logic and Syntax Errors:**
              - [list detected errors from the ChatGPT response]
            - **Potential Issues:**
              - [list possible issues]
            - **Suggestions:**
              - [list possible improvements]

            _Review was generated by ChatGPT._
