name: Automated Code Review

on:
    pull_request:
        types: [opened, reopened, synchronize]

jobs:
  code-review:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

    #   - name: Install dependencies
    #     run: sudo apt-get update && sudo apt-get install -y jq

      - name: Run automated code review
        env:
          GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
          GITHUB_EVENT_PATH: ${{ github.event_path }}
        run: |
          chmod +x scripts/automated-code-review.sh
          scripts/automated-code-review.sh "$GEMINI_API_KEY"

      - name: Remove previous Code Review comments
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const { owner, repo } = context.repo;
            const prNumber = context.issue.number;
            const { data: comments } = await github.rest.issues.listComments({ owner, repo, issue_number: prNumber });
            for (const comment of comments) {
              if (comment.body.startsWith("## Code Review Report") && comment.user.login === "github-actions[bot]") {
                await github.rest.issues.deleteComment({ owner, repo, comment_id: comment.id });
              }
            }

      - name: Post code review comment
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PR_NUMBER: ${{ github.event.pull_request.number }}
        run: |
          REVIEW=$(cat review.txt)
          COMMENT_BODY=$(jq -nc --arg body "$REVIEW" '{"body": $body}')
          curl -s -X POST \
            -H "Authorization: token $GITHUB_TOKEN" \
            -H "Content-Type: application/json" \
            -d "$COMMENT_BODY" \
            "https://api.github.com/repos/${{ github.repository }}/issues/$PR_NUMBER/comments"

      - name: Upload Gemini response artifact
        uses: actions/upload-artifact@v4
        with:
          name: review-response
          path: full_response.json
